###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    webserver:
        container_name: frontend-web
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - './:/app'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8081:80'
        networks:
            - app-network

    php-fpm:
        container_name: frontend-fpm
        build: phpdocker/php-fpm
        working_dir: /app
        volumes:
            - './:/app'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
        networks:
            - app-network

networks:
    app-network:
        external: true