name: 'Monorepo Split'

on:
  push:
    branches:
      - main
    tags:
      - '*'



jobs:
  provide_packages_json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        env:
          # 1. for Github split
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - uses: "ramsey/composer-install@v1"

      # get package json list
      - id: output_data
        #        run: echo "::set-output name=::"
        run: echo matrix=$(vendor/bin/monorepo-builder packages-json) >> $GITHUB_OUTPUT

    outputs:
      matrix: ${{ steps.output_data.outputs.matrix }}

  split_monorepo:
    needs: provide_packages_json
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.provide_packages_json.outputs.matrix)}}
    steps:
      #      - uses: actions/checkout@v2
      #      - name: Monorepo Split of ${{ matrix.package }}
      #        uses: symplify/github-action-monorepo-split@master
      #        env:
      #          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #        with:
      #          package-directory: 'packages/${{ matrix.package }}'
      ##           split-repository-organization: 'your-organization'
      #          split-repository-name: '${{ matrix.package }}'
      #          user-name: "aminalali8"
      #          user-email: "amin@bunnyshell.com"
      - uses: actions/checkout@v2

      # no tag
      - if: "!startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@2.1"
        env:
          # 1. for Github split
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          # ↓ split "packages/easy-coding-standard" directory
          package_directory: 'packages/${{ matrix.package }}'

          # ↓ into https://github.com/symplify/easy-coding-standard repository
          repository_organization: 'monorepo-sample'
          repository_name: '${{ matrix.package }}'

          # [optional, with "github.com" as default]
#          repository_host: git.private.com:1234

          # ↓ the user signed under the split commit
          user_name: "Amin A.D."
          user_email: "amin@bunnyshell.com"

      # with tag
      - if: "startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@2.1"
        env:
          # 1. for Github split
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag: ${GITHUB_REF#refs/tags/}

          # ↓ split "packages/easy-coding-standard" directory
          package_directory: 'packages/${{ matrix.package }}'

          # ↓ into https://github.com/symplify/easy-coding-standard repository
          repository_organization: 'monorepo-sample'
          repository_name: '${{ matrix.package }}'

          # [optional, with "github.com" as default]
#          repository_host: git.private.com:1234

          # ↓ the user signed under the split commit
          user_name: "Amin A.D."
          user_email: "amin@bunnyshell.com"
