name: 'Monorepo Split'

on:
  push:
    branches:
      - main

jobs:
  provide_packages_json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - uses: "ramsey/composer-install@v1"

      # get package json list
      - id: output_data
#        run: echo "::set-output name=::"
        run: echo "{matrix}={$(vendor/bin/monorepo-builder packages-json)}" >> $GITHUB_OUTPUT

    outputs:
      matrix: ${{ steps.output_data.outputs.matrix }}

  split_monorepo:
    needs: provide_packages_json

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.provide_packages_json.outputs.matrix)}}
#        package: ${{fromJson(needs.provide_packages_json.outputs.matrix)}}


    steps:
      - run: echo ${{ echo matrix.package }}
      - uses: actions/checkout@v2

      - name: Monorepo Split of ${{ matrix.package }}
        uses: symplify/github-action-monorepo-split@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package-directory: 'packages/${{ matrix.package }}'
#           split-repository-organization: 'your-organization'
          split-repository-name: '${{ matrix.package }}'
          user-name: "aminalali8"
          user-email: "amin@bunnyshell.com"
